communication:
  enable_heartbeat: true
  heartbeat:
    interval_ms: 100
    mavlink_timeout_s: 5.0
    timeout_ms: 500
  zmq_bind_address: 127.0.0.1
  zmq_enable_curve: false
  zmq_host: localhost
  zmq_port: 5555
  zmq_public_key: null
  zmq_secret_key: null
  zmq_server_key: null
custom_settings: {}
debug: false
environment: development
hardware:
  baud_rate: 921600
  control_frequency: 400.0
  mavlink_connection: /dev/ttyUSB0
  planning_frequency: 50.0
  telemetry_frequency: 10.0
logging:
  enable_console: true
  enable_file: false
  file: null
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
planning:
  convergence_tolerance: 0.05
  dt: 0.1
  max_iterations: 15
  obstacle_weight: 1000.0
  position_weight: 100.0
  prediction_horizon: 8
  safety_margin: 1.5
  velocity_weight: 10.0
safety:
  emergency_landing_altitude: 2.0
  max_acceleration: 10.0
  max_altitude: 50.0
  max_velocity: 15.0
  safety_radius: 100.0
security:
  enable_authentication: true
  enable_ssl: false
  secret_key: ''
  ssl_cert_file: null
  ssl_key_file: null
  token_expiry_hours: 24
simulation:
  airsim_host: localhost
  airsim_port: 41451
  enable_visualization: true
  simulation_speed: 1.0
  use_airsim: true
coordinate_frame:
  world_frame: ENU
  enforce_consistency: true
  validate_transforms: true
  auto_detect_frame: false
