# Hardware configuration for DART-Planner
#
# Contributors: Update these values to match your drone's physical parameters.
# All values are SI units unless otherwise noted.

# Distance from center of mass to each motor (meters)
arm_length: 0.225  # [m] Example: 0.225 for 450mm quadcopter

# Maximum thrust each motor can produce at full throttle (Newtons)
max_motor_thrust: 12.0  # [N] Example: 12.0N per motor

# Maximum drag torque each propeller can produce (for yaw axis, Nm)
# This is typically much less than roll/pitch torque. Estimate or use datasheet.
max_propeller_drag_torque: 0.18  # [Nm] Example: 0.18Nm per prop

# Number of arms/motors (e.g., 4 for quad, 6 for hex)
num_arms: 4

# Geometry type (e.g., 'x', 'plus', 'coaxial', etc.)
geometry: 'x'

# Transport-delay compensation settings
transport_delay:
  # Communication/processing delay between estimator and controller (milliseconds)
  # Typical values: 20-30ms for most systems, 10-15ms for optimized systems
  delay_ms: 25.0  # [ms] Transport delay to compensate for
  
  # Control loop period (milliseconds)
  # Should match your actual control loop frequency
  control_loop_period_ms: 5.0  # [ms] = 200Hz control loop
  
  # Enable transport-delay compensation
  enabled: true
  
  # Maximum buffer size to prevent memory issues
  max_buffer_size: 1000

# Add any additional hardware-specific parameters below as needed. 