name: 'Setup Python Environment'
description: 'Setup Python with caching and install dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.10'
  cache-key:
    description: 'Cache key prefix for pip dependencies'
    required: false
    default: 'default'
  install-dev:
    description: 'Whether to install development dependencies'
    required: false
    default: 'true'
  install-ci:
    description: 'Whether to install CI dependencies'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.cache-key }}-${{ hashFiles('**/pyproject.toml', '**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.cache-key }}-
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        # Install base package
        pip install .
        # Install development dependencies if requested
        if [ "${{ inputs.install-dev }}" = "true" ]; then
          pip install "[.dev]"
        fi
        # Install CI dependencies if requested
        if [ "${{ inputs.install-ci }}" = "true" ]; then
          pip install "[.ci]"
        fi 