# Airframe-specific configuration for DART-Planner
# This file contains parameters for different drone types and configurations

# Default airframe configuration
default:
  name: "Generic Quadcopter"
  type: "quadcopter"
  
  # Physical parameters
  mass: 1.5  # kg
  arm_length: 0.25  # m
  propeller_diameter: 0.254  # m (10 inches)
  
  # Motor and propeller limits
  max_thrust: 15.0  # N per motor
  max_rpm: 8000  # RPM
  max_power: 200.0  # W per motor
  
  # Flight envelope
  max_velocity: 15.0  # m/s
  max_acceleration: 8.0  # m/s²
  max_angular_velocity: 3.0  # rad/s
  max_angular_acceleration: 6.0  # rad/s²
  
  # Safety limits
  max_altitude: 120.0  # m (400 ft)
  min_altitude: 0.5  # m
  max_distance: 1000.0  # m
  
  # Control parameters
  control_frequency: 100.0  # Hz
  position_kp: [2.0, 2.0, 2.0]  # Position control gains
  velocity_kp: [1.5, 1.5, 1.5]  # Velocity control gains
  attitude_kp: [8.0, 8.0, 8.0]  # Attitude control gains
  attitude_kd: [2.0, 2.0, 2.0]  # Attitude derivative gains

# DJI F450/F550 style quadcopter
dji_f450:
  name: "DJI F450 Quadcopter"
  type: "quadcopter"
  extends: "default"
  
  mass: 1.2
  arm_length: 0.225
  propeller_diameter: 0.254
  
  max_thrust: 12.0
  max_rpm: 7500
  max_power: 180.0
  
  max_velocity: 12.0
  max_acceleration: 6.0
  max_angular_velocity: 2.5
  max_angular_acceleration: 5.0
  
  max_altitude: 100.0
  max_distance: 800.0

# DJI F550 hexacopter
dji_f550:
  name: "DJI F550 Hexacopter"
  type: "hexacopter"
  extends: "default"
  
  mass: 1.8
  arm_length: 0.275
  propeller_diameter: 0.254
  
  max_thrust: 10.0  # Per motor, but 6 motors
  max_rpm: 7000
  max_power: 150.0
  
  max_velocity: 14.0
  max_acceleration: 7.0
  max_angular_velocity: 2.8
  max_angular_acceleration: 5.5
  
  max_altitude: 120.0
  max_distance: 1000.0

# Racing drone configuration
racing_drone:
  name: "Racing Drone"
  type: "quadcopter"
  extends: "default"
  
  mass: 0.8
  arm_length: 0.15
  propeller_diameter: 0.127  # 5 inches
  
  max_thrust: 20.0
  max_rpm: 12000
  max_power: 300.0
  
  max_velocity: 25.0
  max_acceleration: 15.0
  max_angular_velocity: 8.0
  max_angular_acceleration: 15.0
  
  max_altitude: 50.0
  max_distance: 500.0
  
  # Aggressive control gains for racing
  control_frequency: 200.0
  position_kp: [4.0, 4.0, 4.0]
  velocity_kp: [2.5, 2.5, 2.5]
  attitude_kp: [12.0, 12.0, 12.0]
  attitude_kd: [3.0, 3.0, 3.0]

# Heavy lift hexacopter
heavy_lift:
  name: "Heavy Lift Hexacopter"
  type: "hexacopter"
  extends: "default"
  
  mass: 4.5
  arm_length: 0.4
  propeller_diameter: 0.381  # 15 inches
  
  max_thrust: 25.0
  max_rpm: 5000
  max_power: 400.0
  
  max_velocity: 8.0
  max_acceleration: 4.0
  max_angular_velocity: 1.5
  max_angular_acceleration: 3.0
  
  max_altitude: 150.0
  max_distance: 2000.0
  
  # Conservative control gains for stability
  control_frequency: 50.0
  position_kp: [1.5, 1.5, 1.5]
  velocity_kp: [1.0, 1.0, 1.0]
  attitude_kp: [6.0, 6.0, 6.0]
  attitude_kd: [1.5, 1.5, 1.5]

# Indoor micro drone
indoor_micro:
  name: "Indoor Micro Drone"
  type: "quadcopter"
  extends: "default"
  
  mass: 0.3
  arm_length: 0.08
  propeller_diameter: 0.076  # 3 inches
  
  max_thrust: 5.0
  max_rpm: 15000
  max_power: 50.0
  
  max_velocity: 5.0
  max_acceleration: 3.0
  max_angular_velocity: 4.0
  max_angular_acceleration: 8.0
  
  max_altitude: 10.0
  max_distance: 50.0
  
  # High frequency control for indoor precision
  control_frequency: 250.0
  position_kp: [3.0, 3.0, 3.0]
  velocity_kp: [2.0, 2.0, 2.0]
  attitude_kp: [10.0, 10.0, 10.0]
  attitude_kd: [2.5, 2.5, 2.5]

# Fixed-wing aircraft
fixed_wing:
  name: "Fixed-Wing Aircraft"
  type: "fixed_wing"
  
  # Physical parameters
  mass: 2.0
  wingspan: 1.5
  wing_area: 0.5
  
  # Engine limits
  max_thrust: 30.0
  max_power: 500.0
  
  # Flight envelope
  max_velocity: 25.0
  min_velocity: 8.0  # Stall speed
  max_acceleration: 5.0
  max_angular_velocity: 1.0
  max_angular_acceleration: 2.0
  
  # Safety limits
  max_altitude: 200.0
  min_altitude: 10.0
  max_distance: 5000.0
  
  # Control parameters
  control_frequency: 50.0
  position_kp: [1.0, 1.0, 1.0]
  velocity_kp: [0.8, 0.8, 0.8]
  attitude_kp: [4.0, 4.0, 4.0]
  attitude_kd: [1.0, 1.0, 1.0]

# VTOL (Vertical Takeoff and Landing) aircraft
vtol:
  name: "VTOL Aircraft"
  type: "vtol"
  
  # Physical parameters
  mass: 3.0
  wingspan: 2.0
  wing_area: 0.8
  
  # Motor limits (both vertical and horizontal)
  max_vertical_thrust: 40.0
  max_horizontal_thrust: 25.0
  max_power: 600.0
  
  # Flight envelope
  max_velocity: 20.0
  max_acceleration: 6.0
  max_angular_velocity: 2.0
  max_angular_acceleration: 4.0
  
  # Safety limits
  max_altitude: 150.0
  min_altitude: 1.0
  max_distance: 3000.0
  
  # Control parameters
  control_frequency: 100.0
  position_kp: [2.0, 2.0, 2.0]
  velocity_kp: [1.5, 1.5, 1.5]
  attitude_kp: [6.0, 6.0, 6.0]
  attitude_kd: [1.5, 1.5, 1.5] 