import numpy as np
from dataclasses import dataclass, field
from typing import List, Optional

@dataclass
class DroneState:
    """Represents the complete state of the drone at a single point in time."""
    timestamp: float
    position: np.ndarray = field(default_factory=lambda: np.zeros(3))
    velocity: np.ndarray = field(default_factory=lambda: np.zeros(3))
    attitude: np.ndarray = field(default_factory=lambda: np.zeros(3)) # Roll, Pitch, Yaw
    angular_velocity: np.ndarray = field(default_factory=lambda: np.zeros(3))
    motor_rpms: Optional[np.ndarray] = field(default_factory=lambda: np.zeros(4))

@dataclass
class ControlCommand:
    """Represents the output of the low-level controller, sent to the motors."""
    thrust: float
    torque: np.ndarray = field(default_factory=lambda: np.zeros(3)) # Roll, Pitch, Yaw moments

@dataclass
class Trajectory:
    """Represents a time-indexed sequence of desired states, generated by the planner."""
    timestamps: np.ndarray
    positions: np.ndarray
    velocities: Optional[np.ndarray] = None
    accelerations: Optional[np.ndarray] = None
    attitudes: Optional[np.ndarray] = None
    yaws: Optional[np.ndarray] = None
    yaw_rates: Optional[np.ndarray] = None 