name: Release Docker Image

on:
  push:
    tags:
      - "v*.*.*"  # Match semver-like tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image for tagged release
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          TAG=${GITHUB_REF_NAME}
          IMAGE=ghcr.io/${OWNER_LC}/dart-planner:${TAG}
          LATEST=ghcr.io/${OWNER_LC}/dart-planner:latest
          echo "Building $IMAGE and $LATEST"
          docker build -t $IMAGE -t $LATEST -f demos/Dockerfile .
          docker push $IMAGE
          docker push $LATEST
