name: Release Docker Image

on:
  push:
    tags:
      - "v*.*.*"  # Match semver-like tags

# Cancel in-progress runs on new commits to same tag
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image for tagged release
        uses: docker/build-push-action@v5
        with:
          context: .
          file: demos/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dart-planner:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/dart-planner:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
