name: "🔎 E2E Playwright Test Suite"

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install Python dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
          pip install -r requirements/dev.txt

      - name: "Install Playwright browsers"
        run: |
          python -m playwright install --with-deps

      - name: "Run E2E Playwright tests"
        env:
          DART_SECRET_KEY: e2e_test_secret_key_value_123456789
        run: |
          pytest -m e2e tests/e2e/ 