#
# SITL (Software-In-The-Loop) TEST WORKFLOW
# This workflow focuses specifically on SITL testing and simulation validation.
# Code quality checks are now handled by quality-pipeline.yml
# Simulation stack tests have been consolidated from sim-suite.yml

name: DART-Planner SITL Tests

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

# Cancel in-progress runs on new commits to same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  AIRSIM_VERSION: '1.8.1'

jobs:
  simulation-stack-tests:
    runs-on: ubuntu-latest
    name: Simulation Stack Tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-sitl-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-sitl-
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install -r requirements/dev.txt
        
    - name: Run Simulation Stack Tests
      run: |
        echo "🧪 Running simulation stack integration tests..."
        # Test simulation stack initialization
        python scripts/run_sim_stack.py --test-mode --timeout 60
        
        # Test simulation communication
        python scripts/test_simulation_communication.py
        
        # Test simulation shutdown
        python scripts/test_simulation_cleanup.py
        
    - name: Run Simulation Performance Tests
      run: |
        echo "⚡ Running simulation performance tests..."
        pytest tests/test_simulation_performance.py -v
      continue-on-error: true  # Performance tests may vary in CI
      
    - name: Upload simulation test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: simulation-test-results
        path: results/simulation/

  unit-tests:
    runs-on: ubuntu-latest
    name: SITL Unit Tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-sitl-unit-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-sitl-unit-
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
        pip install -e .
        
    - name: Run SITL unit tests
      run: |
        pytest tests/test_sitl_unit_tests.py -v --tb=short
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-results
        path: test-results/
        
  mock-sitl-tests:
    runs-on: ubuntu-latest
    name: Mock SITL Tests
    needs: [simulation-stack-tests, unit-tests]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-sitl-mock-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-sitl-mock-
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
        pip install -e .
        
    - name: Run mock SITL tests
      run: |
        python scripts/run_sitl_tests.py --config smoke --mock --timeout 300
        
    - name: Upload mock test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mock-sitl-results
        path: results/sitl/
        
  airsim-sitl-tests:
    runs-on: windows-latest  # AirSim works best on Windows
    name: AirSim SITL Tests
    needs: mock-sitl-tests
    # Only run on schedule, manual trigger, or when explicitly requested
    if: |
      github.event_name == 'schedule' || 
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[full-test]') ||
      contains(github.event.pull_request.title, '[full-test]') ||
      contains(github.event.pull_request.body, '[full-test]')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-airsim-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-airsim-
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
        pip install -e .
        
    - name: Cache AirSim binary
      id: cache-airsim
      uses: actions/cache@v4
      with:
        path: AirSim
        key: ${{ runner.os }}-airsim-${{ env.AIRSIM_VERSION }}
        restore-keys: |
          ${{ runner.os }}-airsim-
        
    - name: Download and setup AirSim
      if: steps.cache-airsim.outputs.cache-hit != 'true'
      run: |
        # Download AirSim binary (Windows)
        Invoke-WebRequest -Uri "https://github.com/Microsoft/AirSim/releases/download/v${{ env.AIRSIM_VERSION }}/AirSimNH-Windows.zip" -OutFile "AirSim.zip"
        Expand-Archive -Path "AirSim.zip" -DestinationPath "AirSim"
        
        # Copy AirSim settings
        Copy-Item "airsim_settings.json" -Destination "$env:USERPROFILE\Documents\AirSim\settings.json"
        
    - name: Start AirSim
      run: |
        # Start AirSim in background
        Start-Process -FilePath "AirSim\WindowsNoEditor\AirSimNH.exe" -ArgumentList "-windowed", "-ResX=640", "-ResY=480"
        
        # Wait for AirSim to start
        Start-Sleep -Seconds 30
        
    - name: Test AirSim connection
      run: |
        python scripts/test_airsim_connection.py
        
    - name: Run AirSim SITL smoke tests
      run: |
        python scripts/run_sitl_tests.py --config smoke --timeout 600
      timeout-minutes: 15
      
    - name: Run AirSim SITL performance tests
      run: |
        python scripts/run_sitl_tests.py --config performance --timeout 900
      timeout-minutes: 20
      continue-on-error: true  # Performance tests may fail due to CI environment
      
    - name: Upload AirSim test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: airsim-sitl-results
        path: results/sitl/
        
    - name: Upload AirSim logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: airsim-logs
        path: logs/ 