#
# NIGHTLY/COMPREHENSIVE TEST SUITE
# This workflow runs only on a schedule or manual trigger. It covers slow and integration tests.
# All slow/integration tests should be run here. Do not duplicate in other workflows.

name: Slow / Comprehensive Test Suite

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 03:00 UTC

# Cancel in-progress runs on new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  slow-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python
        with:
          python-version: '3.10'
          cache-key: 'slow-suite'
          install-dev: 'true'
          install-ci: 'false'

      - name: Run slow test suite with coverage
        env:
          MPLBACKEND: Agg
        run: pytest -m 'slow' -n auto --cov=dart_planner --cov=src --cov-report=xml

      - name: Upload coverage artefact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml 