#
# NIGHTLY/COMPREHENSIVE TEST SUITE
# This workflow runs only on a schedule or manual trigger. It covers slow and integration tests.
# All slow/integration tests should be run here. Do not duplicate in other workflows.

name: Slow / Comprehensive Test Suite

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 03:00 UTC

jobs:
  slow-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
          pip install -r requirements/dev.txt

      - name: Run slow test suite with coverage
        env:
          MPLBACKEND: Agg
        run: pytest -m 'slow' -n auto --cov=dart_planner --cov=src --cov-report=xml

      - name: Upload coverage artefact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml 